apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: toolrent
type: Opaque
data:
  # Base64 encoded values (mismo usuario/contraseña del monolito)
  # postgres -> cG9zdGdyZXM=
  # 1234 -> MTIzNA==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTIzNA==

