apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: toolrent
data:
  # URLs de servicios
  EUREKA_URL: "http://eureka-server:8761/eureka/"
  CONFIG_SERVER_URL: "http://config-server:8888"
  # Keycloak corriendo en K8s (comunicación interna)
  KEYCLOAK_ISSUER_URI: "http://keycloak:8090/realms/ToolRent"
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8090/realms/ToolRent/protocol/openid-connect/certs"

  # Configuración de bases de datos (hosts y puertos)
  DB_PORT: "5432"

