apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-clients
  namespace: toolrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-clients
  template:
    metadata:
      labels:
        app: ms-clients
    spec:
      containers:
      - name: ms-clients
        image: brandonusach/toolrent-ms-clients:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-server:8888"
        - name: DB_HOST
          value: "postgres-clients-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "clients_db"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: EUREKA_URL
          value: "http://eureka-server:8761/eureka/"
        - name: KEYCLOAK_ISSUER_URI
          value: "http://keycloak:8090/realms/toolrent-realm"
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-clients
  namespace: toolrent
spec:
  type: ClusterIP
  selector:
    app: ms-clients
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

