apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-clients
  namespace: toolrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-clients
  template:
    metadata:
      labels:
        app: ms-clients
    spec:
      containers:
      - name: ms-clients
        image: brandonusach/toolrent-ms-clients:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres-clients-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "clients_db"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: EUREKA_URL
          value: "http://eureka-server:8761/eureka/"
        - name: KEYCLOAK_ISSUER_URI
          value: "http://keycloak:8080/realms/toolrent-realm"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ms-clients
  namespace: toolrent
spec:
  type: ClusterIP
  selector:
    app: ms-clients
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

