server:
  port: 0

spring:
  application:
    name: ms-loans
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-loans-service}:${DB_PORT:5432}/${DB_NAME:loans_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8090/realms/ToolRent}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8090/realms/ToolRent/protocol/openid-connect/certs}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"

# URLs de otros microservicios (a través de Eureka)
microservices:
  inventory:
    url: http://ms-inventory
  clients:
    url: http://ms-clients
  rates:
    url: http://ms-rates
  kardex:
    url: http://ms-kardex

